trigger:
  branches:
    include:
      - main

pool:
  name: Default

variables:
  - group: AzureServicePrincipal

  - name: acrLoginServer
    value: lexitasgeotest-gecubragfndnhvgk.azurecr.io

  - name: imageName
    value: ros-dlq-alert

  - name: resourceGroupName
    value: Internal-POC

  - name: functionAppEast
    value: lexitasgeoreplication

  - name: functionAppCentral
    value: lexitasgeoreplication-1

stages:
  - stage: BuildPush
    jobs:
      - job: BuildPush
        steps:
          - task: AzureCLI@2
            inputs:
              azureSubscription: 'AzureRM-Geo'
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                echo "Logging in to ACR..."
                az acr login --name "$(az acr list --query "[?loginServer=='${acrLoginServer}'].name" -o tsv)"

                echo "Building Docker image from lEXITASGEOTEST..."
                docker build -t "$acrLoginServer/$imageName:latest" -f lEXITASGEOTEST/Dockerfile lEXITASGEOTEST/

                echo "Pushing Docker image to ACR..."
                docker push "$acrLoginServer/$imageName:latest"
            env:
              acrLoginServer: $(acrLoginServer)
              imageName: $(imageName)

  - stage: Deploy
    dependsOn: BuildPush
    jobs:
      - job: DeployEast
        displayName: Deploy to East US
        steps:
          - task: AzureCLI@2
            inputs:
              azureSubscription: 'AzureRM-Geo'
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                echo "Deploying to Function App in East US..."
                az functionapp config container set \
                  --name "$functionAppEast" \
                  --resource-group "$resourceGroupName" \
                  --docker-custom-image-name "$acrLoginServer/$imageName:latest"

                az functionapp restart \
                  --name "$functionAppEast" \
                  --resource-group "$resourceGroupName"
            env:
              acrLoginServer: $(acrLoginServer)
              imageName: $(imageName)
              functionAppEast: $(functionAppEast)
              resourceGroupName: $(resourceGroupName)

      - job: DeployCentral
        displayName: Deploy to Central US
        steps:
          - task: AzureCLI@2
            inputs:
              azureSubscription: 'AzureRM-Geo'
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                echo "Deploying to Function App in Central US..."
                az functionapp config container set \
                  --name "$functionAppCentral" \
                  --resource-group "$resourceGroupName" \
                  --docker-custom-image-name "$acrLoginServer/$imageName:latest"

                az functionapp restart \
                  --name "$functionAppCentral" \
                  --resource-group "$resourceGroupName"
            env:
              acrLoginServer: $(acrLoginServer)
              imageName: $(imageName)
              functionAppCentral: $(functionAppCentral)
              resourceGroupName: $(resourceGroupName)