trigger:
  branches:
    include:
      - main  # or your working branch

pool:
  name: Default

variables:
  - group: AzureServicePrincipal

  - name: acrLoginServer
    value: lexitasgeotest-gecubragfndnhvgk.azurecr.io

  - name: functionAppName
    value: lexitas-geo-test

  - name: imageName
    value: ros-dlq-alert

  - name: resourceGroupName
    value: Internal-POC

stages:
  - stage: BuildPushDeploy
    jobs:
      - job: BuildPushDeploy
        steps:
          - task: AzureCLI@2
            inputs:
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                echo "Logging in to Azure..."
                az login --service-principal \
                  --username "$AZURE_CLIENT_ID" \
                  --password "$AZURE_CLIENT_SECRET" \
                  --tenant "$AZURE_TENANT_ID"

                echo "Logging in to ACR..."
                az acr login --name "$acrLoginServer"

                echo "Building Docker image..."
                docker build -t "$acrLoginServer/$imageName:latest" .

                echo "Pushing Docker image to ACR..."
                docker push "$acrLoginServer/$imageName:latest"

                echo "Deploying to Azure Function App..."
                az functionapp config container set \
                  --name "$functionAppName" \
                  --resource-group "$resourceGroupName" \
                  --docker-custom-image-name "$acrLoginServer/$imageName:latest"

                echo "Restarting Function App..."
                az functionapp restart \
                  --name "$functionAppName" \
                  --resource-group "$resourceGroupName"
            env:
              AZURE_CLIENT_ID: $(AZURE_CLIENT_ID)
              AZURE_CLIENT_SECRET: $(AZURE_CLIENT_SECRET)
              AZURE_TENANT_ID: $(AZURE_TENANT_ID)
              acrLoginServer: $(acrLoginServer)
              imageName: $(imageName)
              functionAppName: $(functionAppName)
              resourceGroupName: $(resourceGroupName)
